language: generic
sudo: required

services:
   - docker

before_install:
   - docker build -t clorking/docker-cicd-nodejs-test-client-test -f ./client/Dockerfile.dev ./client #naming...

script:
   # - docker run clorking/docker-cicd-nodejs-test-client-test -- --coverage
   - docker run -e CI=true clorking/docker-cicd-nodejs-test-client-test npm test

after_success:
   - docker build -t clorking/docker-cicd-nodejs-test-client ./client
   - docker build -t clorking/docker-cicd-nodejs-test-nginx ./nginx
   - docker build -t clorking/docker-cicd-nodejs-test-server ./server
   - docker build -t clorking/docker-cicd-nodejs-test-worker ./worker
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker push clorking/docker-cicd-nodejs-test-client
   - docker push clorking/docker-cicd-nodejs-test-nginx 
   - docker push clorking/docker-cicd-nodejs-test-server
   - docker push clorking/docker-cicd-nodejs-test-worker

deploy:
   provider: elasticbeanstalk
   region: ap-southeast-2
   app: docker-cicd-nodejs-test
   env: DockerCicdNodejsTest-env-1
   bucket_name: elasticbeanstalk-ap-southeast-2-067138989400
   bucket_path: docker-cicd-nodejs-test
   on:
      branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY